// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PruebasTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void casoPrueba1() {
    // Test name: CasoPrueba1
    // Step # | name | target | value
    // 1 | open | http://sahitest.com/demo/training/login.htm | 
    driver.get("http://sahitest.com/demo/training/login.htm");
    // 2 | setWindowSize | 892x728 | 
    driver.manage().window().setSize(new Dimension(892, 728));
    // 3 | click | name=user | 
    driver.findElement(By.name("user")).click();
    // 4 | type | name=user | test
    driver.findElement(By.name("user")).sendKeys("test");
    // 5 | click | name=password | 
    driver.findElement(By.name("password")).click();
    // 6 | type | name=password | secret
    driver.findElement(By.name("password")).sendKeys("secret");
    // 7 | click | css=.button | 
    driver.findElement(By.cssSelector(".button")).click();
    // 8 | click | css=tr:nth-child(2) | 
    driver.findElement(By.cssSelector("tr:nth-child(2)")).click();
    // 9 | type | name=q | 2
    driver.findElement(By.name("q")).sendKeys("2");
    // 10 | click | css=tr:nth-child(3) | 
    driver.findElement(By.cssSelector("tr:nth-child(3)")).click();
    // 11 | type | css=tr:nth-child(3) input | 1
    driver.findElement(By.cssSelector("tr:nth-child(3) input")).sendKeys("1");
    // 12 | click | css=tr:nth-child(4) input | 
    driver.findElement(By.cssSelector("tr:nth-child(4) input")).click();
    // 13 | type | css=tr:nth-child(4) input | 3
    driver.findElement(By.cssSelector("tr:nth-child(4) input")).sendKeys("3");
    // 14 | click | css=input:nth-child(4) | 
    driver.findElement(By.cssSelector("input:nth-child(4)")).click();
    // 15 | click | css=#available > input:nth-child(5) | 
    driver.findElement(By.cssSelector("#available > input:nth-child(5)")).click();
    // 16 | click | css=input:nth-child(6) | 
    driver.findElement(By.cssSelector("input:nth-child(6)")).click();
  }
  @Test
  public void casoPrueba2() {
    // Test name: CasoPrueba2
    // Step # | name | target | value
    // 1 | open | http://sahitest.com/demo/training/login.htm | 
    driver.get("http://sahitest.com/demo/training/login.htm");
    // 2 | setWindowSize | 892x728 | 
    driver.manage().window().setSize(new Dimension(892, 728));
    // 3 | click | linkText=Register | 
    driver.findElement(By.linkText("Register")).click();
    // 4 | click | id=uid | 
    driver.findElement(By.id("uid")).click();
    // 5 | type | id=uid | test
    driver.findElement(By.id("uid")).sendKeys("test");
    // 6 | click | id=pid | 
    driver.findElement(By.id("pid")).click();
    // 7 | type | id=pid | secret
    driver.findElement(By.id("pid")).sendKeys("secret");
    // 8 | click | id=pid2 | 
    driver.findElement(By.id("pid2")).click();
    // 9 | type | id=pid2 | secret
    driver.findElement(By.id("pid2")).sendKeys("secret");
    // 10 | click | name=gender | 
    driver.findElement(By.name("gender")).click();
    // 11 | click | id=taid | 
    driver.findElement(By.id("taid")).click();
    // 12 | type | id=taid | Cra 16 25-34
    driver.findElement(By.id("taid")).sendKeys("Cra 16 25-34");
    // 13 | click | id=btaid | 
    driver.findElement(By.id("btaid")).click();
    // 14 | type | id=btaid | Cra 16 25-34
    driver.findElement(By.id("btaid")).sendKeys("Cra 16 25-34");
    // 15 | click | name=state | 
    driver.findElement(By.name("state")).click();
    // 16 | select | name=state | label=Tamil Nadu
    {
      WebElement dropdown = driver.findElement(By.name("state"));
      dropdown.findElement(By.xpath("//option[. = 'Tamil Nadu']")).click();
    }
    // 17 | click | name=state | 
    driver.findElement(By.name("state")).click();
    // 18 | click | name=agree | 
    driver.findElement(By.name("agree")).click();
    // 19 | click | css=input:nth-child(5) | 
    driver.findElement(By.cssSelector("input:nth-child(5)")).click();
    // 20 | assertAlert | Registered Successfully | 
    assertThat(driver.switchTo().alert().getText(), is("Registered Successfully"));
    // 21 | click | linkText=Go back to login | 
    driver.findElement(By.linkText("Go back to login")).click();
    // 22 | click | name=user | 
    driver.findElement(By.name("user")).click();
    // 23 | type | name=user | test
    driver.findElement(By.name("user")).sendKeys("test");
    // 24 | click | name=password | 
    driver.findElement(By.name("password")).click();
    // 25 | type | name=password | secret
    driver.findElement(By.name("password")).sendKeys("secret");
    // 26 | click | css=.button | 
    driver.findElement(By.cssSelector(".button")).click();
    // 27 | click | name=q | 
    driver.findElement(By.name("q")).click();
    // 28 | type | name=q | 5
    driver.findElement(By.name("q")).sendKeys("5");
    // 29 | click | css=tr:nth-child(3) input | 
    driver.findElement(By.cssSelector("tr:nth-child(3) input")).click();
    // 30 | type | css=tr:nth-child(3) input | 2
    driver.findElement(By.cssSelector("tr:nth-child(3) input")).sendKeys("2");
    // 31 | click | css=tr:nth-child(4) input | 
    driver.findElement(By.cssSelector("tr:nth-child(4) input")).click();
    // 32 | type | css=tr:nth-child(4) input | 3
    driver.findElement(By.cssSelector("tr:nth-child(4) input")).sendKeys("3");
    // 33 | click | css=input:nth-child(4) | 
    driver.findElement(By.cssSelector("input:nth-child(4)")).click();
    // 34 | click | css=input:nth-child(6) | 
    driver.findElement(By.cssSelector("input:nth-child(6)")).click();
  }
}
