// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TESTCASE1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tESTCASE1() {
    // Test name: TESTCASE1
    // Step # | name | target | value
    // 1 | open | http://blackrockdigital.github.io/startbootstrap-sb-admin/dist/login.html | 
    driver.get("http://blackrockdigital.github.io/startbootstrap-sb-admin/dist/login.html");
    // 2 | setWindowSize | 892x728 | 
    driver.manage().window().setSize(new Dimension(892, 728));
    // 3 | click | id=inputEmailAddress | 
    driver.findElement(By.id("inputEmailAddress")).click();
    // 4 | type | id=inputEmailAddress | diego@prueba.com
    driver.findElement(By.id("inputEmailAddress")).sendKeys("diego@prueba.com");
    // 5 | click | id=inputPassword | 
    driver.findElement(By.id("inputPassword")).click();
    // 6 | type | id=inputPassword | 0000
    driver.findElement(By.id("inputPassword")).sendKeys("0000");
    // 7 | click | css=.custom-control-label | 
    driver.findElement(By.cssSelector(".custom-control-label")).click();
    // 8 | click | linkText=Login | 
    driver.findElement(By.linkText("Login")).click();
  }
}
